MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  # TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
  TRAIN: ("clora_data2_train_amodal",)
  TEST: ("clora_data2_val_amodal",)
SOLVER:
  # IMS_PER_BATCH: 2
  # BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  STEPS: (430000, 590000)
  MAX_ITER: 640000
INPUT:
  MASK_FORMAT: "rle"
  # IMG_SIZE: (640, 480)
  COLOR_AUGMENTATION: True
  PERLIN_DISTORTION: False
  CROP_RATIO: 0.5
  AMODAL: False 
  DEPTH: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
VERSION: 2


