MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS: 500
DATASETS:
  # OURS: False
  TRAIN: ("clora_data2_train_amodal",)
  TEST: ("clora_data2_val_amodal",)
SOLVER:
  # IMS_PER_BATCH: 2
  # BASE_LR: 0.0025
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  # STEPS: (640000, 1000000)
  # MAX_ITER: 1280000
  STEPS: (430000, 590000)
  MAX_ITER: 640000
INPUT:
  MASK_FORMAT: "rle"
  # IMG_SIZE: (640, 480)
  COLOR_AUGMENTATION: True
  PERLIN_DISTORTION: False
  CROP_RATIO: 0.5
  AMODAL: False 
  DEPTH: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
